### ISSUE TITLE
EC3K

### ISSUE THREAD

**Issue by olluz** [SevenW/embapps#1]
Hi SevenWatt,
sorry to bother you, but can any of these be used with a Jeelink v3c (RFM69) to receive EC3K data ?
Thanks in advance!

**Comment by SevenW** [comment]
This implementation is specific for the LPC8xx micro-controllers. It would require some coding in the jeelib environment to get this done. One would need to reinitialize several RFM69 registers to start receiving EC3K. The settings can be taken from this git, file rf69cc.h

Jean-Claude already had a EC3K sketch for the jeenode. With a little adaptation of configuring the RFM69 it should work.

Maybe you can seek help on the jeelabs forum.

SevenW
